xfactor/config/routes.rb
Xfactor::Application.routes.draw do
  
  resources :contestants

  root :to => 'contestants#index'

end

xfactor/app/models/contestant.rb
class Contestant < ActiveRecord::Base
  validates :name, :talent, presence: true
  validates :talent, length: {minimum: 5}
end

xfactor/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

xfactor/app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  # GET /contestants
  # GET /contestants.json
  def index
    @contestants = Contestant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contestants }
    end
  end

  # GET /contestants/1
  # GET /contestants/1.json
  def show
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/new
  # GET /contestants/new.json
  def new
    @contestant = Contestant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/1/edit
  def edit
    @contestant = Contestant.find(params[:id])
  end

  # POST /contestants
  # POST /contestants.json
  def create
    @contestant = Contestant.new(params[:contestant])

    respond_to do |format|
      if @contestant.save
        format.html { redirect_to @contestant, notice: 'Contestant was successfully created.' }
        format.json { render json: @contestant, status: :created, location: @contestant }
      else
        format.html { render action: "new" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contestants/1
  # PUT /contestants/1.json
  def update
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      if @contestant.update_attributes(params[:contestant])
        format.html { redirect_to @contestant, notice: 'Contestant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contestants/1
  # DELETE /contestants/1.json
  def destroy
    @contestant = Contestant.find(params[:id])
    @contestant.destroy

    respond_to do |format|
      format.html { redirect_to contestants_url }
      format.json { head :ok }
    end
  end
end

xfactor/app/helpers/application_helper.rb
module ApplicationHelper
end

xfactor/app/helpers/contestants_helper.rb
module ContestantsHelper
end

xfactor/app/views/contestants/_form.html.erb
<%= form_for(@contestant, validate: true) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :talent %><br />
    <%= f.text_area :talent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

xfactor/app/views/contestants/edit.html.erb
<h1>Editing contestant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contestant %> |
<%= link_to 'Back', contestants_path %>

xfactor/app/views/contestants/index.html.erb
<h1>Listing contestants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Talent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contestants.each do |contestant| %>
  <tr>
    <td><%= contestant.name %></td>
    <td><%= contestant.talent %></td>
    <td><%= link_to 'Show', contestant %></td>
    <td><%= link_to 'Edit', edit_contestant_path(contestant) %></td>
    <td><%= link_to 'Destroy', contestant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contestant', new_contestant_path %>

xfactor/app/views/contestants/new.html.erb
<h1>New contestant</h1>

<%= render 'form' %>

<%= link_to 'Back', contestants_path %>

xfactor/app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contestant.name %>
</p>

<p>
  <b>Talent:</b>
  <%= @contestant.talent %>
</p>


<%= link_to 'Edit', edit_contestant_path(@contestant) %> |
<%= link_to 'Back', contestants_path %>

xfactor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xfactor</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>